---
name: quasimoto
version: "{{major}}.{{minor}}.{{patch}}"
description: A lossless audio generator.
entry: {{entry}}
requirements:
  - mido
  - vcorelib
  - runtimepy
  - scipy
  - matplotlib
dev_requirements:
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: gen
    description: "generate audio"

mypy_local: |
  [mypy-scipy.*]
  ignore_missing_imports = True

  [mypy-pyaudio.*]
  ignore_missing_imports = True

  [mypy-mido.*]
  ignore_missing_imports = True
